#!/usr/bin/env python3
"""Regenerate ``openrct2_ride_generator/_ride_metadata.py`` from decoded RCT2 objects.

The car-bearing ride types (the 3x3 building rides and the animated flat rides)
each clone a vanilla RCT2 ride *type*, so their gameplay / packaging metadata --
the fixed car-entry fields, the peep loading-waypoint table, the default
capacity, the build-menu category and the shelter flag -- must match that
vanilla object. Rather than hand-transcribe 60-entry waypoint arrays into Python
(error-prone, and exactly the toil this script removes), we read OpenRCT2's
*decoded* RCT2 ride objects -- the JSON the engine emits under
``object/rct2/ride/`` -- and write them into a generated data module the
generator imports.

The two fields the exporter fills in per *object* are stripped out here, because
they are not part of the cloned ride type:

* ``numSeats`` -- the ride capacity. Kept separately as ``default_seats`` (the
  loader lets a config override it).
* ``hasAdditionalColour1`` / ``hasAdditionalColour2`` -- derived by the exporter
  from the remap regions the mesh's materials actually use.

This is a DEV tool. The generated module is checked in, so the generator never
needs the RCT2 objects at runtime -- only to regenerate when adding a ride type.

Usage:
    uv run python scripts/extract_ride_metadata.py [--object-dir DIR]
"""
from __future__ import annotations

import argparse
import json
import pprint
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "openrct2_ride_generator" / "_ride_metadata.py"

# A decoded-object directory under a sibling OpenRCT2 checkout (a build artifact:
# OpenRCT2 writes the JSON form of the bundled RCT2 objects there). Override with
# --object-dir for a different checkout / build folder.
DEFAULT_OBJECT_DIR = (
    REPO.parent.parent / "OpenRCT2" / "cmake-build-debug" / "object" / "rct2" / "ride"
)

# generator ride_type -> decoded RCT2 object id (file rct2.ride.<id>.json). Only
# the car-bearing rides clone a vanilla object; shops / facilities have their car
# synthesized by the engine, so they carry no metadata here.
RIDE_OBJECTS: dict[str, str] = {
    "crooked_house": "chbuild",
    "haunted_house": "hhbuild",
    "circus": "circus1",
    "3d_cinema": "c3d",
    "merry_go_round": "mgr1",
    "ferris_wheel": "fwh1",
    "twist": "twist1",
    "enterprise": "enterp",
    "motion_simulator": "simpod",
    "swinging_ship": "swsh1",
    "space_rings": "srings",
}

# Car-entry fields the exporter supplies per object (not part of the ride type).
_DYNAMIC_CAR_FIELDS = frozenset(
    {"numSeats", "hasAdditionalColour1", "hasAdditionalColour2", "loadingWaypoints"}
)


def _extract(object_dir: Path, ride_type: str, object_id: str) -> dict[str, Any]:
    path = object_dir / f"rct2.ride.{object_id}.json"
    props = json.loads(path.read_text())["properties"]
    car = dict(props["cars"])
    waypoints = car.pop("loadingWaypoints", None)
    fixed_car = {k: v for k, v in car.items() if k not in _DYNAMIC_CAR_FIELDS}
    return {
        "category": props["category"],
        "has_shelter": bool(props.get("hasShelter", False)),
        "default_seats": int(props["cars"]["numSeats"]),
        "cars_per_flat_ride": int(props.get("carsPerFlatRide", 1)),
        "car": fixed_car,
        "waypoints": waypoints,
    }


def build(object_dir: Path) -> dict[str, dict[str, Any]]:
    return {
        ride_type: _extract(object_dir, ride_type, object_id)
        for ride_type, object_id in RIDE_OBJECTS.items()
    }


def render_module(metadata: dict[str, dict[str, Any]]) -> str:
    body = pprint.pformat(metadata, width=96, sort_dicts=False)
    return (
        '"""Per-ride-type gameplay / packaging metadata cloned from the vanilla\n'
        "RCT2 ride objects.\n\n"
        "AUTO-GENERATED by scripts/extract_ride_metadata.py -- do not edit by hand.\n"
        "Regenerate with: uv run python scripts/extract_ride_metadata.py\n"
        '"""\n\n'
        "from typing import Any\n\n"
        f"RIDE_METADATA: dict[str, dict[str, Any]] = {body}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--object-dir", type=Path, default=DEFAULT_OBJECT_DIR,
        help="decoded RCT2 ride object directory (default: a sibling OpenRCT2 build)",
    )
    args = parser.parse_args()
    if not args.object_dir.is_dir():
        parser.error(f"object dir not found: {args.object_dir}")
    metadata = build(args.object_dir)
    OUT.write_text(render_module(metadata))
    print(f"wrote {OUT.relative_to(REPO)} ({len(metadata)} ride types)")


if __name__ == "__main__":
    main()
